### ISSUE TITLE
R version 4.3.2 note supported

### ISSUE THREAD

**Issue by vgdeven** [coatless-mac/macrtools#12]
I have been trying to install the compiler toolchain for Mac. I already have the Xcode CLI installed but when I try `macos_rtools_install()` the following error pops up -- `Error in cat("R version", getRversion(), "is not supported. Please upgrade.\n") : 
  argument 2 (type 'list') cannot be handled by 'cat'` Don't think I am doing anything wrong.

```
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] macrtools_0.0.0.9000

loaded via a namespace (and not attached):
[1] compiler_4.3.2  tools_4.3.2     curl_5.1.0      remotes_2.4.2.1 sys_3.4.2       askpass_1.2.0 
```

This is my current session info

**Comment by coatless** [comment]
ewk! Let me look into that.

**Comment by vgdeven** [comment]
Thanks very much!

**Comment by coatless** [comment]
@vgdeven Thanks again for the report. It looks like the problematic line was in the `gfortran_install()` as it checked for whether the macOS version was supported. In this case, the operating system wasn't bumped to macOS Sonoma (14.0.0). Thus, you were getting that error. 

The error message was improved and fixed in: https://github.com/coatless-mac/macrtools/commit/8292fc6e8076c77ed7914067f4c1d1725a84325b

We've subsequently bumped the supported version up to macOS 14

**Comment by coatless** [comment]
Feel free to try again using the latest version:

```r
install.packages("remotes")
remotes::install_github("coatless-mac/macrtools")
macrtools::macos_rtools_install()
```
